name: meamo
display_name: Meamo theme by studiocitrus.pl
version: 1.0.0
author:
  name: "Studiocitrus"
  email: "biuro@studiocitrus.pl"
  url: "http://studiocitrus.pl"

meta:
  compatibility:
      from: 1.7.0.0
      to: ~

  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-cms:
      name: Layuot for CMS pages
      description: Takes care of custom pages depending on page ID
    layout-categories-top:
      name: Categories layout
      description: Layout with categories on top

assets:
  # If you're using this theme as child and you want to load
  # the parent theme assets, uncomment this line.
#  use_parent_assets: true

  # The following lines are showing how to load assets in your page
  # Uncomment and change value to start loading css or js files
 css:
   all:
     - id: meamo-dist-all-styles
       path: assets/css/meamo.min.css
#    product:
#      - id: product-style
#        path: assets/css/product.css
#        media: all
#        priority: 200
 js:
   all:
     - id: meamo-dist-all-scripts
       path: assets/js/meamo.min.js
#    cart:
#      - id: cat-extra-lib
#        path: assets/js/cart-lib.js


global_settings:
  configuration:
    PS_IMAGE_QUALITY: png
  modules:
   to_enable:
     - ps_linklist
  hooks:
    modules_to_hook:
      displayNav1:
        - ps_mainmenu
        - ps_customersignin
        - ps_socialfollow
        - ps_searchbar
        - ps_shoppingcart
        # - ps_wishlist TODO:
        - ps_currencyselector
        - ps_languageselector
      displayNav2:
        - ps_currencyselector
        - ps_customersignin
        - ps_shoppingcart
        - ps_languageselector
      displayMobile1:
        - ps_mainmenu
        - ps_customersignin
        - ps_socialfollow
        - ps_searchbar
        - ps_shoppingcart
        # - ps_wishlist TODO:
        - ps_currencyselector
        - ps_languageselector
      displayTop:
        - ps_mainmenu
        - ps_searchbar
      displayHome:
        - ps_imageslider
        - ps_customtext
        - ps_featuredproducts
        - ps_banner
      displayFooterBefore:
        - ps_emailsubscription
        - ps_socialfollow
      displayFooter:
        - ps_linklist
        - ps_customeraccountlinks
        - ps_contactinfo
      displayTopCategories:
        - ps_categorytree
      displayLeftColumn:
        - ps_categorytree
        - ps_facetedsearch
      displaySearch:
        - ps_searchbar
      displayProductAdditionalInfo:
        - ps_sharebuttons
      displayFooterProduct:
        - ps_featuredproducts_2
      displayReassurance:
        - blockreassurance
      displayOrderConfirmation2:
        - ps_featuredproducts
      displayCrossSellingShoppingCart:
        - ps_featuredproducts

  image_types:
    cart_default:
      width: 125
      height: 125
      scope: [products]
    small_default:
      width: 98
      height: 98
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 452
      height: 452
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 380
      height: 570
      scope: [products]
    large_default:
      width: 800
      height: 1200
      scope: [products, manufacturers, suppliers]
    category_default:
      width: 141
      height: 180
      scope: [categories]
    stores_default:
      width: 170
      height: 115
      scope: [stores]

theme_settings:
  default_layout: layout-full-width
  layouts:
    category: layout-categories-top
    best-sales: layout-categories-top
    new-products: layout-categories-top
    prices-drop: layout-categories-top
    contact: layout-categories-top
    cms: layout-cms
